### ISSUE TITLE
Steamdeck .net Installation fix ?

### ISSUE THREAD

**Issue by Sowelimun** [BrainwreckedTech/dmm#1]
pretty new to this so feel free to delete this if it isnt relevant.
so ive installed this on my steam deck and it always gave me an ".NET missing or not installed" error.

found out its bc the Microsoft .Net folder was missing from the Program Files(x86) Folder of the dmm prefix. Only had it bc i dragged it over from another installation of the same .Net version.
could just be user error or a permission thing too but thought itd be helpful to know for other steamdeck users who struggled to get this to run.

**Comment by BrainwreckedTech** [comment]
Oh, I see the problem.  The link DivaModManager spits out when it can't find .NET gives you a file named `windowsdesktop-runtime-6.0.12-win-x64.exe`.  The link I'm using results in a file called `dotnet-runtime-6.0.12-win-x64.exe`.  My DMM script is retrieving the wrong file.

**Comment by BrainwreckedTech** [comment]
Thanks for reporting this issue.  If it still doesn't work let me know and I'll re-open the issue.

**Comment by Sowelimun** [comment]
so i just git cloned it again to see if it was fixed and it seems now the whole framework is missing. i had to paste several .Net folders to get it to run. Missing folders or folders with missing stuff: ProgramData/Microsoft/NetFramework/BreadcrumbStore/ has no contents, Microsoft.WindowsDesktop.App is missing from shared in the dotnet folder and the microsoft .net folder is still missing from program files (x86).

**Comment by BrainwreckedTech** [comment]
Currently pestering someone I know to see how it works on their Deck since I don't have one.  If `dmm upgrade` can find a version number for .NET Runtime then it _is_ installed.

```
$ dmm upgrade
                 Local Upstream
GE-Proton         7-35     7-35
.NET Runtime    6.0.12   6.0.12

To upgrade components: dmm upgrade <dotnet|proton>
```

**Comment by BrainwreckedTech** [comment]
How did you get past the `pv` requirement, since only flatpaks can be installed in SteamOS Holo?  If you broke Steam OS in anyway to get past that, that's a big oof.

I can make it so `pv` is optional so Steam Deck users don't have to tinker with their system like that.  Progress isn't _that_ big a deal.

**Comment by BrainwreckedTech** [comment]
My volunteer was able to get DivaModManager running on her Steam Deck, so I'll be closing this issue again.

![PXL_20221230_160521231](https://user-images.githubusercontent.com/3752022/210090281-03a884ca-9d19-4e13-98a8-34bf8f272862.jpg)

**Comment by Sowelimun** [comment]
ik this is closed, i just wanted to say you can disable readonly state with `sudo steamos-readonly disable` and then just install pv with pacman. shouldnt have made that big of a difference but ill see if it works now. thanks for the attention btw, i hope i wasnt too annoying seeing as the steamdeck seems to be kindof a nuisance for devs to get their programs running on.

**Comment by BrainwreckedTech** [comment]
My volunteer offered to install homebrew to get `pv` but I told her I really don't think breaking the vanilla SteamOS experience on Steam Deck is worth a progress bar for one `tar -x` command.

The only annoying part is not having a particular system to test things out on.  I can use VMs and BTRFS volumes to boot a multitude of Linux OSes on my main machine.  It'd be nice if I could install HoloISO like any other distro, but I think SteamOS Holo assumes complete control of the boot device.

**Comment by BrainwreckedTech** [comment]
![MOV_1772 000000000](https://user-images.githubusercontent.com/3752022/210092117-f3654c05-5007-4716-b447-847a2f93b3c9.png)

Don't let the Holo icon fool you -- I'm just an unoriginal doink and called my Arch + LXQt + Steam setup "Holoesque" as it's meant to be a Steam-gaming-focused installation.  (Like "Steambuntu" two icons to the right.)

"Holoesque" and "Steambuntu" are my checks against my main Arch setup.  They're there to answer the question "Is it just my setup or is this truly broken?"

**Comment by Sowelimun** [comment]
yeah it seems so. i dont think complete control is bad considering its an official steam product and they dont want people to break it but for indie linux devs that is a problem.. also disabling readonly doesnt break anything, you can even enable it again and all of that is recommended by the steam team themselves if you do end up wanting to install something else. its just all gone with the next update. i do like tinkering with the system tho so if you need any further testing on the deck maybe i could help. i can revert about everything i just installed so i dont think testing would be a problem.

edit: just removed pv, turned on readonly and cloned again, now it wont let me past the `command pv not found`. when i run the script itself in a terminal, it does show me it wont be able to show `tar -x` but i cant do anything in there. whatever i type (`dmm` , `dmm install` , `dmm remove` even tho i havent installed yet) it always says it cant find `pv`. how did your volunteer make it work? i can make it work but id need to install pv for that.

**Comment by BrainwreckedTech** [comment]
Generally you don't repeatedly `git clone` to update.  Use `git clone` once and then use `git pull` inside the directory to receive updates.  I don't know if repeated `git clone`s can screw up a directory, but it might be best to delete the directory you `git clone`d into and start fresh.

Make sure you're not running `install.sh` as that's used to install `dmm` and its files to your system under `/usr/local`.  At that point, you'd have to run `install.sh` every time after a `git pull` update.

Just using `dmm` by itself will cause your system to search `${PATH}` for the `dmm` binary.  Specifying `./dmm` says "use this `dmm` right here."

**Comment by Sowelimun** [comment]
tysm! from my pov this is completely fixed. i figured out i ran `install.sh` a while ago and i couldnt delete anything so i just ran it again and now everything works just fine!
