### ISSUE TITLE
/usr/local/bin/dmm is read only (steam deck)

### ISSUE THREAD

**Issue by RubytheScorpion** [BrainwreckedTech/dmm#2]
This occurs when executing the install sh.

**Comment by BrainwreckedTech** [comment]
I just double-checked this, and `/usr/local/bin/dmm` should be installed 755 (`rwxr-xr-x`) no matter what the permissions `<git-repo>/dmm` are.  This is the default of what the `install` command does.  And it allows only root to edit the file.  For everyone else, the file will be read-only.

Should also note that Steam Deck is a special case and `dmm` is designed with allowing you to stay with an immutable root filesystem.  In this case, you shouldn't be installing `dmm` system-wide to `/usr/local/bin` and just execute `dmm` from the directory you cloned the git repo to.  If you choose to unlock the root fs, then yes, you can install `dmm` to `/usr/local/bin`.

Final note:  Even if the file had no permissions, the root user ignores permissions.

**Comment by BrainwreckedTech** [comment]
Closing due to lack of response.
